### PR TITLE
adds choice fields functionality

### PR DESCRIPTION
**Pull request by brianmwadime**

### CODE REVIEW

**Comment by diegostamigni** [comment]
Hi and thanks for the PR. Could you please have a look at why Travis is failing? Thanks

**Comment by brianmwadime** [comment]
No problem, there are some warnings on the validation process. I'll work on fixing those.

**Review by diegostamigni — APPROVED** [review]

**Comment by diegostamigni** [comment]
Thanks @brianmwadime, merged.

**Comment by brianmwadime** [comment]
Appreciated! @diegostamigni

**Pull request merged**
