### PR TITLE
Fixes from Withinapp and Example project update

### PR DESCRIPTION
**Pull request by rivera-ernesto**
Adding signature support.

### CODE REVIEW

**Review by diegostamigni — APPROVED** [review]

**Comment by diegostamigni** [comment]
Hi @rivera-ernesto, thanks for this PR.
Can we make the Travis CI succeed, please? 🙏 Thanks.

**Comment by rivera-ernesto** [comment]
Sure. Let me check.

**Comment by rivera-ernesto** [comment]
Now there are couple of other interesting changes around that could be merged too https://github.com/diegostamigni/UXMPDFKit/network

**Comment by diegostamigni** [comment]
Cool 👍 Do you think you can collect them and open PR for them as well?

**Pull request merged**
